### PR TITLE
Image loading docs

### PR DESCRIPTION
**Pull request by m0ppers**
more docs!

### CODE REVIEW

**Comment by 0b5vr** [comment]
Fixed some explanation and pushed!

**Comment by 0b5vr** [comment]
Ahhhh... I couldn't dealt with your pull request correctly so you aren't showing as contributor...
It is my first merging experience so forgive me...

**Comment by 0b5vr** [comment]
Anyway, I should reorganize some tutorial materials. thank you for your contributing!

**Comment by m0ppers** [comment]
nooooooo! then it seems I need to contribute more :D Just getting started :D

thank you for this great nonsense :D

**Comment by 0b5vr** [comment]
Yaay, your contribution is welcome! 😻

**Pull request closed without merging**
